server:
  port: 9005

spring:
  application:
    name: stats-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
smartlearn:
  jwt:
    secret: "SmartLearnAI-Secret-Key-For-HS256-ChangeMe-123456"
    expire-millis: 86400000   # 24 小时
